### ISSUE TITLE
Filter should work on certain article fields but not identity fields

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Publication-Manager#1]
Here is a complete list of fields that it would be nice if the filter worked on. Some of these are more important than others. For example, targetAuthorInstitutionalAffiliationArticleScopusLabel
and targetAuthorInstitutionalAffiliationArticlePubmedLabel are more important than publicationDateDisplay. So if you would like me to prioritize, please let me know.

```
pmid
pmcid
publicationDateDisplay
doi
publicationTypeCanonical
scopusDocID
issn
journalTitleISOabbreviation
journalTitleVerbose
articleTitle
lastName [for any author]
firstName [for any author]
emailMatch
identityOrganizationalUnit
articleAffiliation
journalSubfieldScienceMetrixLabel
journalSubfieldDepartment
targetAuthorInstitutionalAffiliationIdentity
targetAuthorInstitutionalAffiliationArticleScopusLabel
targetAuthorInstitutionalAffiliationArticleScopusAffiliationId
targetAuthorInstitutionalAffiliationArticlePubmedLabel
nonTargetAuthorInstitutionalAffiliationMatchKnownInstitution
institutionGrant
articleGrant
```

**Comment by paulalbert1** [comment]
Filter should not be on identity data.

<img width="1154" alt="Screen Shot 2019-09-27 at 11 28 25 AM" src="https://user-images.githubusercontent.com/3651640/65781665-04f3da00-e11a-11e9-8485-f3c21366a2e4.png">

**Comment by sarbajitdutta** [comment]
I disagree @paulalbert1 . It should be on both.

**Comment by paulalbert1** [comment]
Having just disambiguated 300 people, I disagree with your disagreement. I offered the above example because I wanted to find candidate articles that were `LIKE '%derm%'`. Well, I'm not getting that because every last candidate article returned is a match, because "Dermatology" is listed in the journal category. As an alternative, I have taken to doing Command-F which is not ideal. 

The place to learn about a person is in the "Manage profile" section.

If I'm missing something, let me know.

**Comment by paulalbert1** [comment]
@vav4001 - This satisfies the stated use case, but it takes away an existing functionality: the ability to filter on multiple words. Here's an example. Could you please address this?

<img width="1170" alt="Screen Shot 2020-03-11 at 7 38 25 AM" src="https://user-images.githubusercontent.com/3651640/76413235-742d5580-636b-11ea-960c-98263aad8fee.png">

**Comment by paulalbert1** [comment]
fixed
