### ISSUE TITLE
Create "Review Suggestions" page for individual 

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Publication-Manager#10]
As per this mockup
https://www.dropbox.com/s/eatfl0calv9htgt/ReCiter_Design_Nov18-2019.xd?dl=0

Sort should provide options for sort by:
- Score ▼
- Score ▲
- Date ▲
- Date ▼

Could we ensure that the relationships line up if any one is several lines of content, or is this a pain??

Modifications:
- Do not include rounded version of user's headshot. We have to use the rectangular version that is made available via Weill Cornell's API
- Towards the top right, it should say, "Add new record: PubMed[link]"

**Comment by paulalbert1** [comment]
Hey @vav4001 . Here is some feedback on the latest round of commits.... In 95% of these cases, I am either: 
- clicking on the elements to find what the CSS should be 
- comparing how this version looks to what I see in the mockup 

## Top (below header navbar)

- Missing the "Review Suggestions" text in the top left, which is 250px from the left side and 75px from the top. Note how this header is on almost every page and in the same place. Here are the key attributes: `font-family: 1898Sans, OpenSans; font-size: 21px; letter-spacing: -0.48px; color: #323942;`


## Name, title, and headshot

- Please make headshot 144px wide (the native size of this image)
- Headshot should be left aligned with left edge of "Suggested" tab
- After increasing size of the headshot so it's 144px, name and title should be vertically in the middle of the headshot.


## Tabs and filters

- Tab height for Suggested, Accepted, and Rejected tabs should be 51px. They should all be immediately on top of the gray band below. No gap!
- Text in the tabs should be 15px from the bottom of the tab
- Text in the tabs should be in the vertical middle compared to the number count. Right now, they're aligned with the bottom of the number.
- There should be no visible border-bottom between the active tab and the gray bar below
- The top border of the gray band below the tabs should be consistently "solid 1px #9b9b9b;". Right now, it's consistent.
- Size of "Filter......." text should be 15px and letter-spacing = -0.19px
- The "Filter...." input box is not vertically aligned with the other buttons.
- The "Filter...." input box, "Sort by" select menu, and "50" select menu should have `border: solid 1px #474747; background-color: #ffffff;` and `margin-bottom: 37px`
- There should be no "Add Publication" tab. It should be a right-aligned link that says, "Add New Record: PubMed[#]" like so: https://zpl.io/V4oPnW0
- The "Sort by score | v" dropdown should have one and only one other option: "Sort by date", which it should literally say. 
- There should be nothing else in the option including the "|" or any arrows or triangles.
- The "Sort by score" text and the non-selected option in the other option in the dropdown should be 15px
- When you click on the dropdown, the options should be left aligned with the left edge of the dropdown. As an example for alignment, see here: https://bit.ly/2TQx93f
- The "50" dropdown should have more left padding.
- Right now, the options in the 50 dropdown are not styled. Please style them so "20" and "10" are in the same font, padding, etc. as "50"
- When I click "50", the options should appear below similar to this dropdown: https://bit.ly/2TQx93f
- For both the "Sort by score" and "50" dropdown, there is a "|" that separates the text from the blue triangles. This should be `width: 2px; height: 22px; border: solid 1px #474747;`




## Article records and evidence table 

- Delete this: "Not finding what you're looking for? Search PubMed..."
- The evidence table should extend all the way to the gray. Right now, it stops short by about 10px on each side.
- Clicking "Show evidence behind this suggestion" sometimes makes the data above (Authors, Title...) jump around. https://bit.ly/3cJi2Bc That shouldn't happen.
- "publication-author-highlighted" class should have background-color = #bfd901 and height = 33px. This may require experimenting with line-height.
- There should be no space between "Authors", "Title", "Journal", "Date" and ":"
- As previously requested, please try to vertically line up the evidence rows between the second and third columns.  
  - current version: https://bit.ly/336wH52
  - mockup: https://bit.ly/38FNAF1
- The labels "Evidence", "Institutional Data", and "Article Data" should be 15px and have letter-spacing = 0.17px
- The row that contains those labels should have height of 38px
- Don't use <small> in the left "Evidence" column for the point values (5.2 points). It should be 14px.
- The text in the badges (for example, "Co-investigator") should be font-size = 10px, letter-spacing = 0.11px, and font-family = OpenSans-Bold, and border = 0.
- Where this is listed "Score of article without clustering: 15.45, Average score of cluster: 9.42", the numbers should be in bold
- The bottom of the PubMed and GET IT buttons should be vertically aligned with the "Show evidence behind this suggestion" link
- letter-spacing of .h6fnhWdeg-publication-field should be 0.18px



## Sidebar

- As shared in the feedback on sidebar, "Review suggestions" should be highlighted on this page and that highlight should extend all the way to the sides of the sidebar.


## Bottom sort and pagination bar

- "Show records" should be 14px.
- .pagination-container should extend on the left to the sidebar and all the way to the right edge of the screen.
- As it stated in the mockup...
  - `.page_link {width: 14px; height: 12.3px;  font-family: HelveticaNeue;  font-size: 10px;  font-weight: bold; font-stretch: normal; font-style: normal; line-height: normal; letter-spacing: normal; text-align: center; color: #5b5b5b;}`
  - `.pgntn_bg_active {width: 31px; height: 31px; border: solid 1px #bbbbbb; background-color: #efefef;}`
  - `.pgntn_bg {width: 31px; height: 31px; border: solid 0.5px #bbbbbb; background-color: #f9f9f9;}`
  - `.page-item {border: solid 1px #bbbbbb;}`
  - `.page-item .active {background-color: #efefef; color: #5b5b5b;}`
- Consistent with the mockup here (https://zpl.io/b6BkB5y), the links in the pagination bar should be like so.
  - If there's 1 page of results, display "1[no link]" (The selected page is not a link of course.)
  - If there are 2-5 pages of results, display "First 1 2 3 4 5 Last"
  - If there are 6+ pages of results, display "First 1 2 ◀ ... ▶ 5 6 Last"
    - For "◀" and "▶", please use the png images in the mockup for those triangles.
    - "..." is not a link. The text should be `{color: #5b5b5b;}`
- The buttons in the pagination bar should be `border: solid 0.5px #bbbbbb; background-color: #f9f9f9;`

**Comment by paulalbert1** [comment]
Also, please don't display "accept all" or "reject all" if there are no records in that tab.
<img width="888" alt="Screen Shot 2020-03-13 at 12 11 31 PM" src="https://user-images.githubusercontent.com/3651640/76639079-e6e13100-6523-11ea-9e18-35b53646136e.png">

**Comment by paulalbert1** [comment]
@vav4001 - Please don't forget to look at the UI and compare it to the mockup.

By combining these in the same attribute, you are including padding-left and padding-top two times
`.reviewSuggestionHeading, reviewSuggestionHeading h3`

<img width="1204" alt="Screen Shot 2020-03-20 at 2 04 06 PM" src="https://user-images.githubusercontent.com/3651640/77192933-c11fd300-6ab3-11ea-86a5-222ad73de89e.png">

**Comment by paulalbert1** [comment]
Dropdown says 50 but this is only showing 20.

<img width="1370" alt="Screen Shot 2020-03-20 at 4 44 29 PM" src="https://user-images.githubusercontent.com/3651640/77204892-1961cf80-6aca-11ea-80de-40ccb030bdc3.png">

**Comment by paulalbert1** [comment]
Hi @vav4001 - Some minor feedback. As per the mockup...

1. Text links here should not be underlined
2. The border between "Sort by score" and the down arrow should be thinner
3. "Sort by score" is slightly lower vertically than "20."
<img width="919" alt="Screen Shot 2020-03-30 at 7 47 57 AM" src="https://user-images.githubusercontent.com/3651640/77910437-1cdd1f80-725d-11ea-9631-693406f899c9.png">

4. First and second buttons are not vertically aligned.
<img width="550" alt="Screen Shot 2020-03-30 at 7 44 49 AM" src="https://user-images.githubusercontent.com/3651640/77910613-69c0f600-725d-11ea-9938-d5525697c4b4.png">
<img width="751" alt="Screen Shot 2020-03-30 at 7 29 02 AM" src="https://user-images.githubusercontent.com/3651640/77910699-9248f000-725d-11ea-99a5-b0bfb0f943ba.png">

5. Mentor badge is off to the right
<img width="808" alt="Screen Shot 2020-03-30 at 7 35 16 AM" src="https://user-images.githubusercontent.com/3651640/77910641-76454e80-725d-11ea-872c-bf1e0380c775.png">

**Comment by paulalbert1** [comment]
@vav4001 - Another issue. The evidence hover is no longer working.

<img width="1386" alt="Screen Shot 2020-03-30 at 2 48 18 PM" src="https://user-images.githubusercontent.com/3651640/77949902-b88a8200-7295-11ea-8d6c-6832f7ded1ff.png">

**Comment by paulalbert1** [comment]
@vav4001 - In the production version of ReCiter, "Accept all" is grayed out (and not clickable) on the "Accept" tab, and "Reject all" is grayed out on the "Reject" tab.

<img width="1147" alt="Screen Shot 2020-04-10 at 12 56 32 PM" src="https://user-images.githubusercontent.com/3651640/79009538-b0e89a00-7b2d-11ea-86ad-5600b76beaf9.png">
<img width="1123" alt="Screen Shot 2020-04-10 at 12 57 46 PM" src="https://user-images.githubusercontent.com/3651640/79009540-b1813080-7b2d-11ea-884a-f4d3edd339ef.png">

**Comment by paulalbert1** [comment]
@vav4001 -  understand that you saw the mockup and concluded that the labels should be left aligned down the page, but it makes the labels look messy. It is probably best to arrange them as you see in the third screenshot which I got from production.

<img width="1160" alt="label spacing" src="https://user-images.githubusercontent.com/3651640/79009616-e7beb000-7b2d-11ea-993a-089406de9547.png">
<img width="1236" alt="labels" src="https://user-images.githubusercontent.com/3651640/79009617-e8574680-7b2d-11ea-9f94-0669941aa2bb.png">


<img width="421" alt="Screen Shot 2020-04-10 at 1 21 05 PM" src="https://user-images.githubusercontent.com/3651640/79009725-353b1d00-7b2e-11ea-9340-523484de1f55.png">

**Comment by paulalbert1** [comment]
@vav4001 - Please use the same backup image you use on the "Review Suggestions" page as on the "Find Scholar" page.

<img width="1294" alt="backup image" src="https://user-images.githubusercontent.com/3651640/79010385-d2e31c00-7b2f-11ea-8708-954d7afeaeb9.png">

**Comment by paulalbert1** [comment]
@vav4001  - Please increase the margin above the show/hide link.

<img width="479" alt="Screen Shot 2020-04-10 at 1 35 13 PM" src="https://user-images.githubusercontent.com/3651640/79010518-20f81f80-7b30-11ea-9b50-8d6c7160ea46.png">

<img width="1269" alt="Screen Shot 2020-04-10 at 12 59 05 PM" src="https://user-images.githubusercontent.com/3651640/79010462-01f98d80-7b30-11ea-8f26-9a3d92121d44.png">

**Comment by paulalbert1** [comment]
@vav4001  - Consistent with the mockup, please use the thinner width for the bar border separating the "Sort by score" text and the triangle.

<img width="1204" alt="weight pipes" src="https://user-images.githubusercontent.com/3651640/79010548-340aef80-7b30-11ea-9dac-cfbe57fb47ea.png">

**Comment by paulalbert1** [comment]
@vav4001 - Please increase the font-size to 14px.

<img width="1124" alt="font size" src="https://user-images.githubusercontent.com/3651640/79010643-60bf0700-7b30-11ea-95a7-0a8ae6810e26.png">

**Comment by paulalbert1** [comment]
@vav4001  - Some individuals have > 1,000 pubs. Circles look pretty but we need an oval in some cases.

<img width="1020" alt="Screen Shot 2020-04-04 at 5 09 56 PM" src="https://user-images.githubusercontent.com/3651640/79011386-eabb9f80-7b31-11ea-8bf6-c0ff064a4ab4.png">

**Comment by vav4001** [comment]
> 
> 
> @vav4001 - Consistent with the mockup, please use the thinner width for the bar border separating the "Sort by score" text and the triangle.
> 
> <img alt="weight pipes" width="1204" src="https://user-images.githubusercontent.com/3651640/79010548-340aef80-7b30-11ea-9dac-cfbe57fb47ea.png">

@paulalbert1 Made the separator thinner in size to align with the mockups.

**Comment by vav4001** [comment]
> 
> 
> @vav4001 - Some individuals have > 1,000 pubs. Circles look pretty but we need an oval in some cases.
> 
> <img alt="Screen Shot 2020-04-04 at 5 09 56 PM" width="1020" src="https://user-images.githubusercontent.com/3651640/79011386-eabb9f80-7b31-11ea-8bf6-c0ff064a4ab4.png">


@paulalbert1  when there are more number of publications we have implemented oval badge for the publication count

**Comment by paulalbert1** [comment]
Fixed
