### ISSUE TITLE
Create "Review Suggestions" page for groups

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Publication-Manager#11]
This does take a while, so we need a spinner for when this is working.

We need an error message if this attempts to return too many results.

Also, see #21. See Sarbajit for details.

**Comment by paulalbert1** [comment]
Consistent with the mockup, please:
1. Put some margin between "Show records" and the dropdown.
2. Some padding in the dropdown
3. Move the triangle down
<img width="877" alt="Screen Shot 2020-04-10 at 12 53 32 PM" src="https://user-images.githubusercontent.com/3651640/79009442-6e26c200-7b2d-11ea-952e-4241b604438c.png">

**Comment by paulalbert1** [comment]
Some more feedback....

<img width="946" alt="Screen Shot 2020-04-10 at 5 29 46 PM" src="https://user-images.githubusercontent.com/3651640/79024455-f66a8e80-7b50-11ea-980e-8a928f0914db.png">
<img width="937" alt="Screen Shot 2020-04-10 at 5 25 52 PM" src="https://user-images.githubusercontent.com/3651640/79024461-f8345200-7b50-11ea-850f-a7045f65eea6.png">

**Comment by vav4001** [comment]
> 
> 
> Consistent with the mockup, please:
> 
>     1. Put some margin between "Show records" and the dropdown.
> 
>     2. Some padding in the dropdown
> 
>     3. Move the triangle down
> 
> 
> <img alt="Screen Shot 2020-04-10 at 12 53 32 PM" width="877" src="https://user-images.githubusercontent.com/3651640/79009442-6e26c200-7b2d-11ea-952e-4241b604438c.png">

@paulalbert1  Based on the feedback we have implemented 
1) Margin between "Show records" and the dropdown.
2) Padding(Changed from 5px to 8px) in the dropdown
3) Moved the triangle down.

**Comment by vav4001** [comment]
> 
> 
> Some more feedback....
> 
> <img alt="Screen Shot 2020-04-10 at 5 29 46 PM" width="946" src="https://user-images.githubusercontent.com/3651640/79024455-f66a8e80-7b50-11ea-980e-8a928f0914db.png">
> 
> <img alt="Screen Shot 2020-04-10 at 5 25 52 PM" width="937" src="https://user-images.githubusercontent.com/3651640/79024461-f8345200-7b50-11ea-850f-a7045f65eea6.png">

@paulalbert1  Now the height of the evidence row resembles as per the mockup, Review Suggestions in the sidebar is higlighted.
Also the url slug has been replaced with "review_suggestions" instead of "individual_suggestions"

**Comment by paulalbert1** [comment]
@vav4001 - I can confirm 2 and 3 are fixed but not 1. The evidence row should look the same whether you are in individual view or group view. 

1) Now the height of the evidence row resembles as per the mockup, 
2) Review Suggestions in the sidebar is higlighted.
3) Also the url slug has been replaced with "review_suggestions" instead of "individual_suggestions"

<img width="1028" alt="Screen Shot 2020-04-21 at 7 46 51 AM" src="https://user-images.githubusercontent.com/3651640/79862570-498bdf00-83a4-11ea-9b5e-518cf658bac5.png">

**Comment by paulalbert1** [comment]
@vav4001  - Note the header. Below is the mockup. This should be consistent with the change you made [here](https://github.com/wcmc-its/ReCiter-Publication-Manager/issues/12#issuecomment-617115720).
<img width="961" alt="Screen Shot 2020-04-21 at 7 54 26 AM" src="https://user-images.githubusercontent.com/3651640/79863971-a9838500-83a6-11ea-8b1b-4745f377bc3e.png">

**Comment by paulalbert1** [comment]
Fixed
