### ISSUE TITLE
Create "Manage Profile" page

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Publication-Manager#12]

**Comment by prideofconcept** [comment]
https://github.com/wcmc-its/ReCiter-Publication-Manager/pull/25 ready for review

(font and sidebar changes are happening in issue 9 PR)

**Comment by paulalbert1** [comment]
@vav4001 - I dare say this is close. I'm just pointing out a couple cosmetic differences. Hopefully this feedback helps.

Note the relevant mockup.
https://app.zeplin.io/project/5e349e97d84f332f293dab4a/screen/5e6000de588192130135bf88

![manageProfile 001](https://user-images.githubusercontent.com/3651640/77849471-ce1a8180-7199-11ea-8570-0aa108f5c1d0.png)

**Comment by paulalbert1** [comment]
@vav4001 - Can we please ensure that these H1s are vertically and horizontally consistent?

<img width="1181" alt="Screen Shot 2020-04-13 at 5 40 46 PM" src="https://user-images.githubusercontent.com/3651640/79164192-8c4f2500-7dae-11ea-9852-0fbcc68d72ad.png">

**Comment by vav4001** [comment]
@paulalbert1  Now the H1s are consistent both vertically and horizontally

**Comment by res3001** [comment]
@paulalbert1 Please advise further on this as there are no open items for DEV team on this.
