### ISSUE TITLE
Session management is not working consistently

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Publication-Manager#53]
The production version of this application uses JSON Web Tokens. JWT is client-based 
and should propagate across all open tabs/windows. It has been tested to not log users out unexpectedly.

Something is different in dev. I notice that when I open multiple tabs, some tabs will automatically log out and others will maintain an open session. This suggests to me that a single session is not being maintained across all tabs/windows.

See video example.

https://www.dropbox.com/s/p9qi2a2q634q42f/SessionManagement-2020-03-23.mov?dl=0

**Comment by ganga** [comment]
@paulalbert1 , can you assign this to me. I am not able to assign it to myself may.

**Comment by ganga** [comment]
@paulalbert1 , I have reproduced this issue after quite a bit of trials. The app is redirecting to Login page when backend is returning 502/503 when we call some apis. But the session still exists and user is not logged out. I verified that cookie session data is still present on login page and when I try to open manage profile, it opens it without any issue.

So the app is redirecting to login page on error though the session is still valid. 
What you want us to do in such cases? Create some default error page and land on that? Please suggest.

**Comment by paulalbert1** [comment]
@ganga, Thanks for investigating. Directing to the login screen doesn't make sense if indeed a user is not logged out. 

As described in #13, the desired behavior in cases of a 502/3 error is to retry after a short interval (4 seconds maybe?). Additionally, in cases where it's retrying, we should show the user something meaningful. We use a spinner during  the initial page load for a given user's profile as you can see below....

<img width="1179" alt="Screen Shot 2020-03-25 at 12 21 08 PM" src="https://user-images.githubusercontent.com/3651640/77559902-22202000-6e93-11ea-9302-c85ec6302d0e.png">

**Comment by paulalbert1** [comment]
@ganga - A couple more thoughts....

To be more explicit:
- If session is active, do NOT direct user to login page. Keep trying.
- If session is inactive, then and only then, direct user to login page.

We should probably have the session length set as a variable in the config file.

**Comment by ganga** [comment]
@paulalbert1 , As of now rety is happening 3 times before failing. One more thing which I have observed is that when we receive 502 from the backend, all the subsequest requests are giving 502.
So if I retry without a limit, it may never load that page as backend seems to never come out of 502. Again this is what I have observed from local connecting to the dev server.

**Comment by paulalbert1** [comment]
Hi @ganga 
- I reproduced the error in Publication Manager production. 
- Looking through the logs, we're not seeing the errors in the ReCiter application itself.
- Therefore, this problem is likely with Publication Manager and independent of changes made to the dev version of PM.

Sarbajit is looking into this.

**Comment by paulalbert1** [comment]
Hi @ganga. Update: we still aren't sure what the problem is. Unless you can identify some bad behavior in the app itself, please move on to other issues. Thanks.

**Comment by ganga** [comment]
Thanks @paulalbert1 , I will move on to other issues.

**Comment by paulalbert1** [comment]
This has been addressed elsewhere.
