### ISSUE TITLE
Create sidebar, header, and footer

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Publication-Manager#9]
As per this mockup
https://weillcornell.invisionapp.com/share/Z6TO9K1KBE9#/screens/405277255

Dropdown menu should just have one option: to log out.

Footer should not be fixed.

Modifications:
- Do not include the logo (as opposed to the logotype)
- Do not include logged in user's headshot

**Comment by prideofconcept** [comment]
There was a comment in Teams - that search should input on enter. I will ensure that is represented

**Comment by paulalbert1** [comment]
##  Sidebar

1. The left edge of the HR should bisect the gear and it should be 28 px from the left edge. The right end should be 32 px from the right edge.

2. The gear and other icons should be 17 px from the left edge.

3. For the headers ("Manage Publications", "Find Scholar"...), please use 
```
font-family: OpenSans;
font-size: 15px;
font-weight: 800;
```

<img width="625" alt="Screen Shot 2020-03-05 at 7 23 17 AM" src="https://user-images.githubusercontent.com/3651640/75981351-55821700-5eb2-11ea-9aa8-7852bf198bc8.png">
<img width="360" alt="Screen Shot 2020-03-05 at 7 22 47 AM" src="https://user-images.githubusercontent.com/3651640/75981353-55821700-5eb2-11ea-95e0-e58c0ada3e4d.png">
<img width="443" alt="Screen Shot 2020-03-05 at 7 22 06 AM" src="https://user-images.githubusercontent.com/3651640/75981354-561aad80-5eb2-11ea-97c2-0c2faf8c7d2d.png">


## Footer

There's a line break after freely available.

Also, there's a strange line (a border-top??) running across the middle in Chrome. Zoom into this image to see what I mean.

<img width="1360" alt="Screen Shot 2020-03-05 at 7 28 51 AM" src="https://user-images.githubusercontent.com/3651640/75981694-07b9de80-5eb3-11ea-87be-0c798101d89a.png">


## Header

Note the updated logo, and positioning of the logo and "Publications Management System."

<img width="647" alt="Screen Shot 2020-03-05 at 7 28 25 AM" src="https://user-images.githubusercontent.com/3651640/75981702-0a1c3880-5eb3-11ea-8a65-e46a6fbc6e75.png">

**Comment by paulalbert1** [comment]
@vav4001 - I noticed that when the screen is between 813 pixels and 1000px, the sidebar overlaps the body of the page.
<img width="845" alt="813px to 1000px wide" src="https://user-images.githubusercontent.com/3651640/79166232-b9053b80-7db2-11ea-8609-1e0848956cff.png">

**Comment by vav4001** [comment]
@paulalbert1 Sidebar will be in collapsed state when the screen is between 813 pixels and 1000px. Implemented sidebar toggle button to make it collapsible and vice versa.

**Comment by res3001** [comment]
@paulalbert1  Please advise further on this. No open items for the dev team on this at this point in time

**Comment by paulalbert1** [comment]
@res3001 - As per the mockup, the "Individual" suboption should not exist below "Find Scholar." Can we do that please?

Also, the "Manage Profile" option should be highlighted when the user is on that page.

<img width="1357" alt="Screen Shot 2020-04-29 at 7 30 03 AM" src="https://user-images.githubusercontent.com/3651640/80591214-49ff2800-89eb-11ea-90e8-e8b1af3db964.png">

<img width="767" alt="Screen Shot 2020-04-29 at 7 32 10 AM" src="https://user-images.githubusercontent.com/3651640/80591367-977b9500-89eb-11ea-86be-bbc44e1ac7f0.png">

**Comment by res3001** [comment]
@paulalbert1  are these both recent changes in the mockup?

**Comment by paulalbert1** [comment]
@res3001 - No. The issue I just pointed with #12 was there from Day 0. 

I asked Irina her memory of the issue with #9. She said the change was "almost in the beginning." That is consistent with my memory too. This was well before any substantive work had been done on 12. I think it was week 2. Mat and I discussed some confusion / inconsistencies with how the search should function, and having only a single screen was the fix to simplify matters. I'm happy to discuss further if you wish.

**Comment by res3001** [comment]
> @res3001 - No. The issue I just pointed with #12 was there from Day 0.
> 
> I asked Irina her memory of the issue with #9. She said the change was "almost in the beginning." That is consistent with my memory too. This was well before any substantive work had been done on 12. I think it was week 2. Mat and I discussed some confusion / inconsistencies with how the search should function, and having only a single screen was the fix to simplify matters. I'm happy to discuss further if you wish.

@paulalbert1  we will come back on this Other than this, please advise if there is any feedback. I have sent you an email with list of open items as well.
